<?php

$localEnvironment = env('APP_ENV', 'production') === 'local';
$defaultPassword = env('DEMO_DEFAULT_PASSWORD', $localEnvironment ? 'lala' : null);

return [
    'enabled' => (bool) env('DEMO_ACCOUNTS_ENABLED', $localEnvironment),
    'full_render_seeders' => (bool) env('RUN_FULL_DEMO_SEEDERS', false),
    'default_password' => $defaultPassword,

    'accounts' => [
        [
            'id' => 1,
            'username' => 'admin',
            'employeeId' => 'AGIS-PLATFORM-001',
            'password' => env('DEMO_ADMIN_PASSWORD', $defaultPassword),
            'name' => 'Juan dela Cruz',
            'firstName' => 'Juan',
            'middleName' => null,
            'lastName' => 'dela Cruz',
            'initials' => 'JD',
            'role' => 'Platform Administrator',
            'roleCode' => 'platform_admin',
            'office' => 'AGIS System Administration',
        ],
        [
            'id' => 2,
            'username' => 'agisadmin',
            'employeeId' => 'AGIS-ADMIN-001',
            'password' => env('DEMO_AGIS_ADMIN_PASSWORD', $defaultPassword),
            'name' => 'Kim V. Lao',
            'firstName' => 'Kim',
            'middleName' => 'V.',
            'lastName' => 'Lao',
            'initials' => 'KL',
            'role' => 'AGIS Administrator',
            'roleCode' => 'agis_admin',
            'office' => 'AGIS System Administration',
        ],
        [
            'id' => 3,
            'username' => 'departmenthead',
            'employeeId' => 'CIAS-HEAD-001',
            'password' => env('DEMO_DEPARTMENT_HEAD_PASSWORD', $defaultPassword),
            'name' => 'Cherrybelle A. Lao',
            'firstName' => 'Cherrybelle',
            'middleName' => 'A.',
            'lastName' => 'Lao',
            'initials' => 'CL',
            'role' => 'CIAS Management',
            'roleCode' => 'cias_management',
            'office' => 'City Internal Audit Office',
        ],
        [
            'id' => 4,
            'username' => 'auditor',
            'employeeId' => 'CIAS-AUD-001',
            'password' => env('DEMO_AUDITOR_PASSWORD', $defaultPassword),
            'name' => 'Marrisa Barcelona',
            'firstName' => 'Marrisa',
            'middleName' => null,
            'lastName' => 'Barcelona',
            'initials' => 'MB',
            'role' => 'AGIS User',
            'roleCode' => 'agis_user',
            'office' => 'City Internal Audit Office',
        ],
        [
            'id' => 5,
            'username' => 'auditee',
            'employeeId' => 'AUDITEE-001',
            'password' => env('DEMO_AUDITEE_PASSWORD', $defaultPassword),
            'name' => 'Maria L. Santos',
            'firstName' => 'Maria',
            'middleName' => 'L.',
            'lastName' => 'Santos',
            'initials' => 'MS',
            'role' => 'Auditee Representative',
            'roleCode' => 'auditee_representative',
            'office' => 'Business Permits and Licensing Division',
        ],
        [
            'id' => 6,
            'username' => 'mayor',
            'employeeId' => 'MAYOR-001',
            'password' => env('DEMO_MAYOR_PASSWORD', $defaultPassword),
            'name' => 'City Mayor',
            'firstName' => 'City',
            'middleName' => null,
            'lastName' => 'Mayor',
            'initials' => 'CM',
            'role' => 'Read Only User',
            'roleCode' => 'read_only',
            'office' => 'Secretary to the Mayor',
        ],
    ],
];
